apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloPythonYZ
  template:
    metadata:
      labels:
        app: helloPythonYZ
    spec:
      containers:
      - name: hello
        image: friendlyhello:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: hello-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: helloPythonYZ
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001